### ISSUE TITLE
Adjust schema

### ISSUE THREAD

**Issue by rglassett** [Ajax4778/MultiVerse#1]
I don't think the current schema is a good model for storing poems and associated stanzas.

Storing the `first_stanza` differently from other stanzas is asking for trouble. Just create a Stanza model when the poem is created.

Why does `last_line` need to be separated from a stanza's `body`?

There doesn't seem to be a way to keep track of where in a poem a stanza occurs. I would drop the `poems.first_stanza` column and add a `stanzas.order` column (integer, the "index" of the stanza in the poem)

Keeping a `poems.completed` column and a `poems.num_stanzas` column seems redundant. If you set the number of stanzas on creation, then a poem is completed when `num_stanzas` equals the count of associated stanzas (and it should be calculated, not stored in a column). If users finalize poems manually, then `num_stanzas` should be calculated instead.

**Comment by ajaxm** [comment]
Done; added stanza.order, removed last_line and poems.completed.
